version: '2.0'
services:
  db:
    image: mysql/mysql-server:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
    - "3306:3306"
    volumes:
    - "./seed.sql:/docker-entrypoint-initdb.d"
  consent-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: consent
    ports:
    - "8080:8080"
    depends_on:
    - db