version: '2.0'
services:
  db:
    image: mysql/mysql-server:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
    - "3306:3306"
    volumes:
    - "./seed.sql:/docker-entrypoint-initdb.d/seed.sql"
  consent-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: consent:updated
      environment:
        CUSTOMERCONSENT_MYSQL_HOST: customerconsent_db_1
        CUSTOMERCONSENT_MYSQL_DB_USER: mysql
        CUSTOMERCONSENT_MYSQL_DB_PASSWORD: mysql
    ports:
    - "8080:8080"
    depends_on:
    - db